config/routes.rb
Blog::Application.routes.draw do
  
  get "home/index"
	
  root :to => 'home#index'

  resources :posts

  resources :posts do
    resources :comments
  end

  match 'search' => 'posts#search'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter, :presence => true
  validates :body, :presence => true, :length => { :minimum => 2 }

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name, :presence => true
  validates :title, :presence => true, :length => { :minimum => 2 }
	
  has_many :comments, :dependent => :destroy

  def self.text_search(query)
    if query.present?
      where("title like :q or content like :q", q: "%#{query}%")
    else
      scoped
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index  
    @posts = Post.paginate(:page => params[:page]).order('id DESC').per_page(5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def search
    @posts = Post.text_search(params[:query]).order('id DESC')
    
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end
  
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @post.name = session[:user_name] || "Nishijima Hidetoshi"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    session[:user_name] = user.name
    redirect_to root_url, notice: "signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def ago( created_at )
    i = (Date.today - created_at.to_date).to_i
    if i < 0 then
      i = 0
    end
    "#{i}d ago"
  end
end

app/views/comments/_comment.html.erb
<p>
	<i class="icon-user"></i> <%= comment.commenter %> 
	<i class="icon-comment"></i> <%= comment.body %>
	<%= link_to [comment.post, comment], :confirm => 'Are you sure?', :method => :delete do %>
	<i class="icon-trash"></i> <% end %>
</p>	

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="field">
		<i class="icon-user"></i>
		<%= f.text_field :commenter, :class => 'text_field span4' %>
	</div>
	<div class="field">
		<i class="icon-comment"></i>
		<%= f.text_area :body, :rows => 5, :class => 'text_area span4' %>
	</div>
	<div class="actions">
		<%= f.submit %>
	<div>	
<% end %>

app/views/home/index.html.erb
<h3>
Kichang Yang
</h3>
+82-10-2859-8121<br />
kcyang.kr@gmail.com<br />

<div class='pull-right'>
<a href="https://twitter.com/zomojj" class="twitter-follow-button" data-show-count="false">Follow @zomojj</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

<br />
<br />

I was excited to see the job posting for the position of Information Security Engineer on Twitter's website. This is exactly the type of position that I have been looking for, and I am sure that I could successfully work as an invaluable team member to improve Twitter's network and infrastructure security.

<br />
<br />

My past experiences as an application security engineer and entrepreneur have given me the ability necessary to work effectively for you. I am also enthusiastic about Twitter's products, as you can see on this website. I will be more than grateful to attend an interview at your convenience.

<br />
<br />

<h4>Entrepreneurial Experience</h4>
<ul>
<li> Founded two companies (one company was acquired)
<li> Co-founder at startups (two companies went public)
</ul>

<br />

<h4>Developer Experience (handle: zomo)</h4>
<ul>
<li> Built an SSL-based encryption & PKI-based authentication system, called "XecureWeb", which is used by four commercial banks in South Korea including <%= link_to "Kookmin Bank", "http://www.kbstar.com" %> 
<li> Implemented security best practices for <%= link_to "Military Manpower Administration of South Korea", "http://www.mma.go.kr" %>
<li> <%= link_to "Proof-of-concept exploit for stack overflow attack (posted to bugtraq, 1996)", "http://archives.neohapsis.com/archives/bugtraq/1996_4/0333.html" %>
<li> <%= link_to "Proof-of-concept exploit for Sendmail (1993)", "http://sites.estvideo.net/f5imv/Securite/how.to.hack.unix.html" %>
<li> Proof-of-concept exploit for DNS spoofing & TCP secquence number prediction attack (1993)
</ul>

<br />

<h4>Skills</h4>
<ul>
<li> Speak Korean(native), English(fluent) and Japanese(advanced)
<li> C, Ruby, Perl, Java, Ruby on Rails, JavaScript, HTML, CSS, Shell scripting, SQL, Solaris & Linux administration
<li> TCP/IP, DNS, Sendmail
<li> Popular encryption algorithms & cryptographic hash functions
</ul>

<br />

<h4>Education</h4>
<ul>
<li> Korea Advanced Institute of Science and Technology, Seoul, Korea
<li> College of Business: Master of Science in Information Engineering
<li> Korea Advanced Institute of Science and Technology, Daejon, Korea
<li> Bachelor of Science in Management
</ul>

<br />

<h4>Links</h4>
<ul>
  <li> <%= link_to "LinkedIn", "http://kr.linkedin.com/in/kichangyang" %>
  <li> <%= link_to "microlog - What I'm doing now (korean)", posts_path %>
  <li> <%= link_to "blog - What I'm thinking now (korean)", "http://zomoblog.heroku.com" %>, Powered by Heroku + Octopress + Twitter Bootstrap Theme + Disqus.
  <li> <%= link_to "pinboard.in - What I'm reading now", "http://pinboard.in/u:kichang/public/" %>
</ul>

<br />

Thank you for considering my application. <br />

<br />

Respectfully yours, <br />

<br />

Kichang Yang <br />

<br />

<h5>This site is built with</h5>
<ul>
<li> Stack: linode VPS + ubuntu lucid + nginx + unicorn + rails + postgresql
<li> Plus: rbenv + Twitter Bootstrap + capistrano + github
</ul>

<h5>Click the pin for my email!</h5>

<p>
<div id="map"></div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kichang Yang</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <script type="text/javascript" src="https://raw.github.com/HPNeo/gmaps/master/gmaps.js"></script>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=deivce-width, initial-scale=1.0">

<script type="text/javascript">
  var map;
  $(document).ready(function(){
    map = new GMaps({
      div: '#map',
      lat: 37.498831,
      lng: 127.022724
    });

    map.addMarker({
      lat: 37.497845,
      lng: 127.027628,
      title: 'Kichang Yang',
      click: function(e) {
        alert('Email: kcyang.kr@gmail.com');
      }
    });

  });
</script>

</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/"><i class="icon-user"></i> Kichang Yang</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "about", "/" %></li>
            <li><%= link_to "microlog", posts_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li> 
              <%= form_tag search_path, method: :get, :class => "navbar-search" do %>
                <%= text_field_tag :query, params[:query], :class => "search-query", :placeholder => "search microlog" %>
              <% end %>
            </li>
			<% if current_user %>				
				<li><%= link_to "sign out #{current_user.name}", signout_path %><li>
			<% else %>
            	<li> <%= link_to "sign in with Twitter", "/auth/twitter" %> </li>
          	<% end %>
			</ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field span4'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area span4', :rows => 5 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary', :value => "#{action} microlog" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = @post.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit microlog") %></h1>
<br>
<%= render :partial => 'form', :locals => {:action => "Update"} %>

app/views/posts/index.html.erb
<%- model_class = Post.new.class -%>

<div class="digg_pagination">
<%= will_paginate @posts, :container => false %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= link_to post.title, post_path(post) %></td>
        <td>
			<% if post.content.match(/^https?:\/\/[\S]+/)%>
			<%= link_to post.content, post.content %>
			<% else %>
			<%= post.content %>
			<% end %>
		</td>
        <td><%= ago(post.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => "ed"),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => "rm"),
                      post_path(post),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => "New microlog"),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = @post.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New microlog") %></h1>
<br>
<%= render :partial => 'form', :locals => {:action => "Create"} %>

app/views/posts/search.html.erb
<h1>Search results</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>
  <tbody>
	<% if @posts.count == 0 %>
	<tr>
		<td>Not found</td>
	</tr>	
	<% end %>
	
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= link_to post.title, post_path(post) %></td>
        <td>
			<% if post.content.match(/^https?:\/\/[\S]+/)%>
			<%= link_to post.content, post.content %>
			<% else %>
			<%= post.content %>
			<% end %>
		</td>
        <td><%= ago(post.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => "ed"),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => "rm"),
                      post_path(post),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/show.html.erb
<%- model_class = @post.class -%>

<p id="notice"><%= notice %></p>

<p>
  <i class="icon-user"></i> <%= @post.name %>
</p>

<p>
  <b><%= @post.title %></b>
</p>

<p>
  <%= @post.content %>
</p>

<%= render @post.comments.order('id ASC') %>

<h4>Add a comment:</h4>
<p>
<%= render "comments/form" %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => "bk"),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => "ed"),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => "rm"),
              post_path(@post),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>